name: Release
on:
  push:
    branches:
      - master
      - beta

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile
      - run: yarn test
      - run: yarn build
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn run semantic-release
